alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias lla='ls -lah'
alias cb='cd ~/ros2_ws && colcon build'
alias cbps='cd ~/ros2_ws && colcon build --packages-select'
alias sil='cd ~/ros2_ws && source install/local_setup.bash'
alias vi='vim'
alias tailpt='tailscale set --exit-node=100.64.87.13'
alias rmall='rm -rf *'
